#!/usr/bin/python

# (c) 2012, Tomas Sedovic <tomas@sedovic.cz>. Licensed under 2-clause BSD.

'''Serves the current directory contents over HTTP.

Usage: localserve [port]

If you don't specify the port, 8000 will be used.
'''

import sys, socket


def start_server():
    try:
        import SimpleHTTPServer  # Python 2
        SimpleHTTPServer.test()
    except ImportError:
        import http.server  # Python 3
        http.server.test(HandlerClass=http.server.SimpleHTTPRequestHandler)


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] in ['-h', '--help']:
        print(__doc__)
        exit(0)

    try:
        start_server()
    except socket.error as err:
        sys.stderr.write('Error: ' + err.strerror + '\n')
        exit(1)
    except KeyboardInterrupt:
        pass
